### ISSUE TITLE
ToDo V 1.0

### ISSUE THREAD

**Issue by LKaemmerling** [LKDevelopment/laravel-refresh-demo#1]
- [x] Logic for "When it should reload" in Browser
- [ ] DatabaseSQLFile Refresher
- [x] Better layout of Popup and "Demo Info Line"  
- [X] Add StyleCI
- [x] Add Tests & Travis
- [x] Add English Translation File
- [ ] Add Console Command to Refresh
- [X] Register on Packagist
